export const CONSTANTS = {
  ERROR_SEND_FORM: {
    NO_ERROR: '0',
    ERROR_TYPE2: '2',
    ERROR_TYPE3: '3',
    DONT_OPEN: ''
  },
  MAX_RESULTS_DROP_DOWN: 7,
  FRIDAY: 'Friday',
  BANKAT: 899,
  yes: 'yes',
  FILTER_lOCATION: '100',
  FILTER_BY_CITY: '300',
  FILTER_BY_BRANCH: '301',
  FILTER_BY_HOURS: '201',
  FILTER_BY_DAYS: '202',
  FILTER_OPEN_NOW: '101',
  FILTER_OPEN_FRIDAY: '103',
  ONLY_ONE_FILTER_ON: ['201', '202', '101', '102'],
  MORNING: {START: '8:30', END: '13:30'},
  NOON: {START: '13:30', END: '20:30'},
  DAY_IN_WEEK: 7,
  PHONE: '2407*',
  HAVE_FAX: 9,
  EVENTS: {
    REFRESH_LIST: 'REFRESH_LIST',
    CLEAN_DROP_DOWN_HOURS: 'CLEAN_DROP_DOWN_HOURS',
    UPDATE_FILTER: 'UPDATE_FILTER',
    UPDATE_BRANCH_FROM_MAP: 'UPDATE_BRANCH_FROM_MAP',
    DELETE_SEARCH: 'DELETE_SEARCH',
    OPEN_LOCATION_POPUP: 'OPEN_LOCATION_POPUP',
    SINGLE_DISPLY: 'SINGLE_DISPLY',
    LIST_CHANGE_FROM_CLICK: 'LIST_CHANGE_FROM_CLICK'
  },
  SERVICES_NUM: 4,
  ROUTES: {
    HOME: {
      BASE: ''
    },
  },
  LANGUAGE: {
    EN: 'en'
  },
  BRANCH_FILTER_NUM: {
    MOBILE: 3,
    TABLET: 5,
    DESKTOP: 7

  },
  UN_SHRINK_DIV_TYPE: {
    REPORT_BAD_HOURS: 'REPORT_BAD_HOURS',
    REPORT_BAD_ADDRESS: 'REPORT_BAD_ADDRESS',
    REPORT_BAD_SERVICE: 'REPORT_BAD_SERVICE'
  },
  ERROR_LINK: 'https://www.bankhapoalim.biz/wps/utils/PoalimP2P'
};
